version: "3"
services:
  tauri_simple_app:
    tty: true
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ".:/app"

  rust_cross_compile_gnu:
    build:
      context: ./docker
      dockerfile: Dockerfile.windows_gnu
    volumes:
      - ".:/app"

  rust_cross_compile_msvc:
    build:
      context: ./docker
      dockerfile: Dockerfile.windows_msvc
    volumes:
      - ".:/app"
