version: '3.3'
services:
  dev_tauri_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    tty: true  # Если нужно что бы сервис был постоянно запущен, даже если не выполняются приложения
    volumes:
      - ..:/app:cached
    command: sleep infinity